repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the linter and automatically fix safe issues
      - id: ruff
        args: [--fix]
      # Run the code formatter
      - id: ruff-format
